intel/goresctrl

pkg/rdt/config.go, pkg/rdt/info.go, pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
- separate info from the control interface:
Better and cleaner to have info as a separate singleton object as other parts (like config and ctrl group management classes) also depend on it.
- don't try to use uninitialized rdt interface
- disable rdt interface if initialization fails
- separate initialization from configuration:
Now SetConfig() must be separately called after Initialize().
=> Initialization fixes

pkg/rdt/config.go
Be consistent and verify basemask in l3AbsoluteAllocation.Overlay(),
similarly to what is done for l3PctRangeAllocation.
=> Verify basemask in l3AbsoluteAllocation.Overlay()

pkg/rdt/config.go
Just print a warning for all cases like we already did when the unit of
allocation was invalid. We're happy as long as the required type of
value (percentage or MBps) is specified.
=> Ignore unrecognized values in MB allocation requests

pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
Deletes all monitoring groups from the ctrl group.
=> Add DeleteMonGroups to CtrlGroup interface

pkg/rdt/rdt.go
Only accept directories that have a tasks file.
=> Improve resctrl group discovery

pkg/rdt/config.go, pkg/rdt/rdt_test.go
If a user specifies that only part of the cache lines should be
allocated for CRI workloads that's probably what she wants.
=> Stop blindly allocating all cache lines

pkg/rdt/info.go
Magically, there were two bugs that happened to counter each other. In
reality, we were not properly parsing the first cache id from L3CODE or
L3DATA schema. However, because the resulting strconv error was ignored
the parsed id was set to 0 which usually happens to be true for the
first cache id.
=> Fix bug in cache id parsing

pkg/rdt/config.go, pkg/rdt/rdt_test.go
Commit b302441eb1bfd08c92c4ef5d42537f6a7d71797c was too aggressive in
saving cache lines. We want to allocate up to the requested total
percentage of cache lines requested. Excess cache lines made available
by rounding errors in the previous passes are "donated" to the last to
be resolved (i.e. biggest) partition.
=> rdt/config: allocate cache lines up to requested total

pkg/log/log.go, pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
This enables blockio to use the same log wrapper package
without duplicating the wrapper.
=> rdt: separate log wrapper to its own package

pkg/cgroups/cgroupblkio.go, pkg/cgroups/cgroupblkio_test.go, pkg/cgroups/cgroupcontrol.go, pkg/cgroups/cgroupcontrol_test.go, pkg/cgroups/cgroupid.go, pkg/cgroups/cgrouppath.go, pkg/cgroups/fsi.go, pkg/cgroups/fsimock.go, pkg/cgroups/fsimock_test.go, pkg/cgroups/fsios.go, pkg/testutils/verify.go
The core of the cgroup filesystem interface is copied from the CRI
Resource Manager pkg/cgroups with a few changes and additions:
- Change cgroupblkio to fully utilize the group-independent cgroup
interface instead of accessing to files directly.
- Add fsios to wrap all accesses to the underlying filesystem.
- Add fsimock to enable testing wanted filesystem contents and
simulating arbitrary errors via user-defined open/read/write
functions.
- Change cgroupblkio unit tests to use fsimock.
- Add unit tests to other modules in the package.
- Add common verifications to testutils package.
=> cgroups: add the cgroup filesystem interface

pkg/rdt/config.go, pkg/rdt/info.go, pkg/rdt/rdt_test.go
Get rid of the obscure empty interfaces. Also, rename the xSchema fields
in the class configuration to xAllocation for consisntency with the
partition configuration.
The dropped negative test cases are now handled at JSON unmarshal time.
=> rdt: specify a well-defined configuration interface

pkg/rdt/bitmask.go, pkg/rdt/config.go, pkg/rdt/info.go, pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
Replace with fmt.Errorf. It was just causing ugly wrapped errors (like
"rdt: err1: rdt: err2...) and hiding problems with call arguments.
=> rdt: drop rdtError

pkg/rdt/config.go, pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
Change slightly obscure SYSTEM_DEFAULT to just DEFAULT.
Also, add an alias so that an empty string can also be used instead of
"DEFAULT" to refer to the root class. This should make the API more
consistent.
=> rdt: change the name of the root group/class to DEFAULT

README.md
Big parts adapted from [CRI-RM RDT documentation](https://intel.github.io/cri-resource-manager/stable/docs/policy/rdt.html)
=> README: add documentation for Intel RDT

pkg/rdt/bitmask.go, pkg/rdt/config.go, pkg/rdt/info.go, pkg/rdt/rdt_test.go
Bitmask is not part of the public API, just an internal helper type.
=> rdt: unexport bitmask type

README.md, pkg/rdt/config.go, pkg/rdt/kubernetes.go, pkg/rdt/kubernetes_test.go, pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
Add ContainerClassFromAnnotations() for retrieving the effective RDT
class of a container from its annotations (container annotations and pod
annotations).
Also, add new per-class configuration options for controlling if a class
may be set via container and pod annotations. Example:
```
partitions:
my-part:
classes:
my-class:
kubernetes:
denyContainerAnnotation: false
denyPodAnnotation: true
```
The 'kubernetes' settings have no effect on resctrl configuration but is
only used when excercising the k8s releated helper functionality,
currently ContainerClassFromAnnotations().
Based on #47
=> rdt: add Kubernetes helpers

pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
Make naming unambiguos/non-overlapping by using something that can't be
a subdir name under /sys/fs/resctrl.
Based on #47
=> rdt: change the name of the root class to system/default

pkg/rdt/kubernetes.go, pkg/rdt/kubernetes_test.go
Make ContainerClassFromAnnotations() fall-through without an error even
if rdt has not been initialized in the case that no rdt-related
annotations are present. If no rdt annotation has been specified we
should not care whether rdt has been actually initialized or not as it's
sort of "no-op".
=> rdt: make ContainerClassFromAnnotations() bit more relaxed

pkg/blockio/kubernetes.go, pkg/kubernetes/annotations.go, pkg/kubernetes/annotations_test.go, pkg/rdt/kubernetes.go
- Add pkg/kubernetes for common annotation handling logic.
- Both blockio and rdt export their own ContainerClassFromAnnotations
functions with the same interface.
- Refactor rdt ContainerClassFromAnnotations to use the common logic.
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> blockio: add ContainerClassFromAnnotations

cmd/sst-ctl/main.go
Very basic skeleton of a sub-command based reference tool for
interfacing with Intel SST. This implementation adds a simple "info"
subcommand for querying the status of SST support and configuration. The
intent is to add specific subcommands for interfacing with each SST
technology (PP, BF, TF and CP).
=> sst: add simple test utility

pkg/blockio/blockio.go, pkg/cgroups/cgroupid.go, pkg/cgroups/cgroupid_linux.go, pkg/cgroups/cgroupid_other.go
Cross-platform builds of projects that use the blockio package fails
because the cgroups package uses the NameToHandleAt syscall (not
available on darwin, freebsd), and because Rdev may not be
uint64 (darwin). However the blockio package may be useful on
non-linux hosts when using OCI output. This patch fixes these build
issues and platforms.
=> cgroups: fix building cgroups on darwin and freebsd

pkg/sst/sst.go
- detect bf and tf even if pp not supported
- fix one misleading error message
=> sst: fixes in sst detection

pkg/rdt/rdt_test.go
Multiple accesses of mg follow, also group access by name,
so it will be complex to handle lack of group gracefully.
=> TestRdt: consider monitor group creation failure a fatal event

Makefile
Let gofmt to write suggested changes to the files instead of
just printing them to stdout. This way we avoid any manual changes
to go files.
=> make: Enable gofmt to write changes

pkg/rdt/config.go, pkg/rdt/rdt_test.go
Fix a bug attempting to write an incorrect (empty) schemata to resctrl
when config of the corresponding control (CAT or MBA) is not specified.
In more detail, an incorrect schemata was generated if CAT was enabled
in the system but no l2/l3allocation was specified in the config (or
similarly MBA was enabled but no mbAllocation was specified in the
config). This patch fixes the error, allocating "100%" (all cache lines
or full memory bandwidth) if nothing is specified in the config. This
aligns with the system default when creating new resctrl groups.
=> rdt: fix default schemata

pkg/utils/sysfs.go
Relies on the intel_uncore_frequency kernel driver that exposes ucore
frequency settings via sysfs and is available since Linux v5.6.
=> utils: add functions for setting uncore frequency limits

pkg/blockio/blockio.go, pkg/blockio/blockio_test.go
minor can be [any number](https://www.kernel.org/doc/Documentation/admin-guide/devices.txt), not necessarily 0.
example:
```
8 block	SCSI disk devices (0-15)
0 = /dev/sda		First SCSI disk whole disk
16 = /dev/sdb		Second SCSI disk whole disk
32 = /dev/sdc		Third SCSI disk whole disk
...
240 = /dev/sdp		Sixteenth SCSI disk whole disk
9 block	Metadisk (RAID) devices
0 = /dev/md0		First metadisk group
1 = /dev/md1		Second metadisk group
```
=> remove check minor must be 0

cmd/blockio/main.go, cmd/sst-ctl/main.go, pkg/blockio/blockio.go, pkg/cgroups/cgroupblkio_test.go, pkg/cgroups/cgroupcontrol.go, pkg/cgroups/cgrouppath.go, pkg/path/path.go, pkg/path/path_test.go, pkg/sst/sst.go, pkg/sst/sst_if.go, pkg/sst/sysfs.go, pkg/utils/msr.go, pkg/utils/sysfs.go
Split into multiple separate patches:
- Add confugurable system prefix
Add new "github.com/intel/goresctrl/pkg/path" package for specifying
global prefix for system directories. This is supposed to be taken into
use by all separate components (cgroup, sysfs. rdt).
- cgroup: add support mount prefix
- sst: add support for specifying mount prefix
- blockio: support mount prefix
The blockio package will follow the global mount prefix specified with
using SetPrefix() from "github.com/intel/goresctrl/pkg/path".
- pkg/utils: support mount prefix
Make the functionality in the utils  package will follow the global
mount prefix specified with using SetPrefix() from
"github.com/intel/goresctrl/pkg/path".
=> Support configurable mount prefix

pkg/blockio/blockio.go, pkg/rdt/info.go, pkg/rdt/rdt.go, pkg/rdt/rdt_test.go, pkg/sst/sysfs.go, pkg/testutils/file.go, pkg/utils/sysfs.go
As of Go v1.17 all of the functionality has been available in the "os" package. The "io/ioutil" is deprecated starting from Go v1.19.
=> Stop using io/ioutil package

pkg/sst/sst.go, pkg/sst/sysfs.go
- separate error if HWP status cannot be determined
Don't return a misleading error that "HWP is not enabled" if we are not actually able to determine whether it's enabled or not.
- don't mask errors on BF enable
=> sst: fixes to BF error handling

.github/workflows/common-codeql.yaml, .github/workflows/common-trivy.yaml, .github/workflows/release.yaml, .github/workflows/trivy-csv.tpl, .github/workflows/verify.yaml
This PR contains multiple enhancements to github workflows.
- split verify in common and per-pr part
This patch specifies concurrency so that earlier jobs on the same PR get
cancelled (if PR is updated in quick succession). Also, it changes the
workflow to take the Go version from the go.mod file, making future
maintenance easier as there is no more need to edit the github workflow
file when bumping Go version.
- github workflows: add trivy scanning
Enable Trivy scanning for licenses and vulnerabilities. This is now
hooked in to the PR verification workflow but it has a common part for
integrating it with other workflows (release, periodic scanning) and
uploading reports as build artefacts.
- github workflows: enable CodeQL analysis
- github workflows: add periodic verify workflow
Add a …
=> Improve github workflows

pkg/blockio/blockio.go, pkg/rdt/rdt.go, pkg/rdt/rdt_test.go
Config file will fail if uknown fields are encountered. Mitigates configuration mistakes e.g. because of typos.
> **NOTE:** this will be a breaking change for existing users having unknown fields in the configuration file
=> Use strict yaml/json unmarshal for config files

go.mod, go.sum, pkg/sst/fuzz_test.go
The test needs to be run as root on an SST-enabled system. Moreover the test manipulates the actual SST configuration of the target system so a dedicated non-production system should be used. Test cannot be parallelized (as it depends on the system state). Because of these precautions the test needs to be explicitly enabled with -sst.system-fuzz flag.
An example how to run the test:
=> sst: add fuzz test for ClosSetup

.github/workflows/common-codeql.yaml, .github/workflows/release.yaml
This is enabled on the release workflow (triggered on new tags).
=> github: enhance codeql action to generate pdf report

.github/workflows/scan-periodic.yaml, .github/workflows/verify.yaml
Only do trivy scanning in the periodic worflow as other results do not change without changing something in the repository.
Also add "on.push" trigger to the verify workflow so that the tip of main branch gets verified.
=> github: add new scan-periodic workflow

doc/rdt.md
I'm using raw bitmasks for configuring partitions and classes. Even though it's obvious that the values for classes are relative to the partition sizes when using `%`, it wasn't obvious to me that the same is true when using raw bitmasks. That's why I add a short description together with an example considering raw bitmasks only.
=> rdt: clarify usage of raw bitmasks

pkg/utils/sysfs.go
We would like to extend the Balloons policy in terms of power management tuning. In particular, we would like to allow users set various CPU frequency scaling governors such as performance, powersave and etc. Since balloons policy can't activate a particular governor by itself, we need to extend the gorecctrl so support tuning of the governors. Once this PR has landed, I will submit a PR against nri-plugins.
=> utils: add functions for setting cpu frequency scaling governor

cmd/rdt/main.go
The monitor sub-command gathers RDT monitoring data as Prometheus metrics and servers those at /metrics HTTP endpoint on a the given port (defaults to 8080).
=> cmd/rdt: add "monitor" sub-command

cmd/rdt/main.go, pkg/log/log.go
Add common helpers to pkg/log that can be utilized in other cmds.
=> cmd/rdt: add cmdline flag to control log level
